### ISSUE TITLE
Sender based routing for multiple senders on the same host

### ISSUE THREAD

**Issue by chrbo** [chrbo/postfix-relay#2]
With the versions (chrb0/postfix:v0.2-alpine-3.19.1-postfix-3.8.6-r0, helm chart v1.1.1-beta) it seems not to be possible to configure multiple senders for the same host.

Example:

```yaml
defaultOutboundRelay:
  host: "[outbound.relay.net]"
  username: sender1@domain.net
additionalOutBoundRelay:
  - sender: noreply@ihr-gesundheitstest.de
     host: "[outbound.relay.net]"
     username: sender2@anotherdomain.net
```

On startup a warning occurs:

```shell
postmap: warning: lmdb:/etc/postfix/sasl_passwd: duplicate entry: "[outbound.relay.net]"
```

And it seems, that postfix does not switch between the accounts for outbound relaying.

In general this scenario should not be a problem. Please see [this link](https://alt.comp.mail.postfix.narkive.com/JIgoZiqB/sasl-passwd-format) for additional information.
